# Project
version=0.2.0
group=dev.obscuria.elixirum
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Ars Elixirum
mod_author=Obscuria
mod_id=elixirum
license=All-Rights-Reserved
credits=Pluvia for care and love, NizorFox for some styles
description=Ars Elixirum is the ultimate extension of potion crafting, applications, and diversity. Through exploration and experimentation, you can create your own recipes to craft Elixirs - powerful replacements for potions - and save and customize them!
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28

# Fabric
fabric_version=0.116.15+1.21.1
fabric_loader_version=0.19.3
fabric_config_version=11.1.136

# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.1.249
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fragmentum
fragmentum_version=1.21.1-2.4.4